server:
  port: 8772
spring:
  profiles: peer2
spring:
  cloud:
    config:
      server:
        git:
          password:
          username:
          uri: https://github.com/pucong/SpringcloudConfig/
          search-paths: respon
      label: master