eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.31.127:8761/eureka/
spring:
  profiles:
    default: peer1
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          password:
          username:
          uri: https://github.com/pucong/SpringcloudConfig/
          search-paths: respon
      label: master