eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.31.127:8761/eureka/
spring:
  profiles:
    default: peer1
  application:
    name: configServer