eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.31.127:8761/eureka/
server:
  port: 8770
spring:
  application:
    name: service-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-one
    api-b:
      path: /api-b/**
      serviceId: service-two