eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://192.168.31.127:8761/eureka/
server:
  port: 8767
spring:
  application:
    name: feign-two
feign:
  hystrix:
    enabled: true